default: &local_defaults
  adapter: postgresql
  host: localhost
  port: 5432
  min_messages: warning
  encoding: utf8
  username: postgres
  password: 
  template: template0

development:
  <<: *local_defaults
  database: rest_development

test:
  <<: *local_defaults
  database: rest_test

staging:
  <<: *local_defaults
  database: rest_development

production:
  <<: *local_defaults
  database: rest_development